<?php

/**
 * @file
 * Custom module that alters forms.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sitephone_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    $form['site_phone'] = [
        '#type' => 'tel',
        '#title' => t('Site phone'),
        '#default_value' => Drupal::config('system.site')->get('phone'),
    ];
    $form['#submit'][] = 'sitephone_system_site_information_phone_submit';
}

function sitephone_system_site_information_phone_submit(array &$form, \Drupal\Core\Form\FormStateInterface $form_state)
{
    $config = Drupal::configFactory()->getEditable('system.site');
    $config->set('phone', $form_state->getValue('site_phone'))->save();
}