<?php

/**
 * Update "Contact Us" form to have a reply message.
 */

function mymodule_update_9000() {
	$contact_form = \Drupal\contact\Entity\ContactForm::load('contactus');
	$contact_form->setReply(t('Thank you for contact ME'));
	$contact_form->save();
}

/**
 * Implements hook_install().
 */
function mymodule_install() {
	// Set the site name.
	\Drupal::configFactory()
		->getEditable('system.site')
		->set('name', 'Dinkbook')
		->save();
}